### PR TITLE
Adds a logo cloud of companies that signed the net neutrality letter

### PR DESCRIPTION
**Pull request by rubbingalcoholic**
This adds a logo cloud to the homepage using a Javascript widget hosted by savenetneutrality.eu. You won't have to worry about adding logos because they're pulled in dynamically using JavaScript.

The remote script include uses a subresource integrity hash to prevent man-in-the-middle attacks (or savenetneutrality.eu being compromised and putting malicious scripts on your site). This prevents us from changing the script, but we won't have to, because it's super simple. It just embeds an iframe on the page and resizes it to fit the logos contained inside. (See the code [here](https://github.com/fightforthefuture/eunetneutrality/blob/master/app/js/logos.js))

See attached screenshot.
screenshot from 2016-07-12 16-42-10

### CODE REVIEW

**Comment by PublicScam** [comment]
Hello @rubbingalcoholic, thanks for this addition.
@socialhack What about other languages? I'm I supposed to deploy this for English only?

**Comment by socialhack** [comment]
Please deploy in English. For other languages we ask volunteers for translations.

**Comment by PublicScam** [comment]
@sqrt2 I tried to deploy this to beta, but the IFrame shows a 301. Is our policy restricting the request?

**Comment by rubbingalcoholic** [comment]
@PublicScam why would the IFrame be redirected to http? The included scripts are always served over HTPPS.

**Comment by PublicScam** [comment]
@rubbingalcoholic 
$ curl -I https://www.savenetneutrality.eu/logos 
HTTP/2.0 301 
date:Wed, 13 Jul 2016 15:54:58 GMT 
content-type:text/html 
set-cookie:__cfduid=dbcbe64b86174774a9eaa07b9009ba87d1468425298; expires=Thu, 13-Jul-17 15:54:58 GMT; path=/; domain=.savenetneutrality.eu; HttpOnly 
location:http://www.savenetneutrality.eu/logos/

**Comment by rubbingalcoholic** [comment]
@PublicScam - that's a bug, thanks for pointing out. I have removed the 301 redirect, but it may take some time and / or a cache clear to resolve depending on your browser. I am now able to use HTTPS on https://www.savenetneutrality.eu/logos/

**Comment by PublicScam** [comment]
@rubbingalcoholic Hi, I cleared the cache twice now and it still doesn't work. Are you sure you've fixed the problem on you server?

**Comment by PublicScam** [comment]
@rubbingalcoholic We've found out what's causing the trouble. I don't think the configuration is supposed as it is, what I can tell though is that it responses differently when requesting `https://www.savenetneutrality.eu/logos/` instead of `https://www.savenetneutrality.eu/logos`. (Note the slash at the end.)
Appending the slash works fine, omitting it causes 201. Your code omits it, which is why it doesn't work. To fix this, I suggest either fixing the configuration of nginx or changing the following line in `logos.js`:
`iframe.src = urlPrefix + '/logos';`
to
`iframe.src = urlPrefix + '/logos/';`

**Comment by tiagocasalribeiro** [comment]
don't know if it helps. https://www.savenetneutrality.eu is also giving an 301 error on this widget. when I inspect the element and add a forward slash at the end of the iframe src address, the widget loads.

**Comment by rubbingalcoholic** [comment]
@PublicScam thanks for figuring this out. I've updated the code to use a trailing slash, and also updated the subresource integrity hash in this repo. Hopefully it should be good to go now. Sorry for the trouble.

**Pull request merged**
