### PR TITLE
Add portuguese translation

### PR DESCRIPTION
**Pull request by tiagocasalribeiro**
I have done the translation to Portuguese, based on the English and Spanish. I double checked it to make sure the translation was acceptable and that I haven't broke anything. There may still be some fuzzy translations or inconsistencies but overall It's ok. I'll also ask some friends to take a look at it and If we spot something I'll get in touch with a correction.

### CODE REVIEW

**Comment by musha68k** [comment]
Thanks!

**Comment by PublicScam** [comment]
@tiagocasalribeiro Hello, did your friends already have a look at it? I just want to know if the translation is ready to go live. It is currently available on beta at beta.savetheinternet.eu. Also, we changed our privacy policy. Maybe you could help us with translating it. If you need help, you can contact me at `publicscam /at/ gmx /dot/ at`.

**Comment by tiagocasalribeiro** [comment]
@PublicScam sorry, my friend and I have been quite busy, we will finish the translation/revision during next week. I'll also look into the privacy policy. Nevertheless the translation is already mature to go live, we will only make minor changes to it.

**Comment by PublicScam** [comment]
@tiagocasalribeiro Alright, that's great to know. PT will go live in the next update.

**Pull request merged**
