### PR TITLE
[DE] Recent changes by @socialhack reviewed/proofread by @sebalis

### PR DESCRIPTION
**Pull request by sebalis**
Some typos and incomplete edits absolutely had to be changed, but I’ve also reinserted a remark in the intro paragraph on traffic management that in my view should not have been deleted (line 44). It makes the threat posed by traffic management much more tangible.

### CODE REVIEW

**Comment by PublicScam** [comment]
Hi @sebalis, thanks for reviewing. Just a quick question in general: Is there a reason for saying 'Sie' in the privacy policy but saying 'Du' in the rest of the page?

**Comment by sebalis** [comment]
I was wondering the same, that was there before I came in. It makes sense to some extent as a separation between call to action and formalitites, I suppose. On a similar note, I have doubts about Du/Deine being capitalised with the recent changes.

**Comment by sebalis** [comment]
(According to [duden.de](http://www.duden.de/sprachwissen/sprachratgeber/gross-oder-kleinschreibung-von--em-du-du--em--und--em-ihr-ihr--em--1) the norm since the reform is lower case “du” etc., but upper case is possible if the text addresses the reader directly, which is of course true for this text.

**Comment by PublicScam** [comment]
The capitalizing might have been myself. I was told today that we agreed on lowercase 'du' for this site. I'll fix that after applying your changes.

**Comment by sebalis** [comment]
I can easily amend the pull request – will do that now.

**Comment by sebalis** [comment]
Now there’s no more upper-case Du or Dein* (except at the start of a sentence of course).

**Pull request merged**
