### PR TITLE
Added DNT policy !! DONT MERGE (YET) !!

### PR DESCRIPTION
**Pull request by maltefiala**
DON'T MERGE!
@socialhack I am guessing Don't Track is respected by piwik.netzfreiheit.org. Please verify. Thanks!

### CODE REVIEW

**Comment by socialhack** [comment]
DNT is taken care of. Cert has expired. I'll poke to fix and report back.

**Comment by socialhack** [comment]
https://piwik.netzfreiheit.org/ cert is fixed. Please re-insert the piwik tracking code from the old website.

**Comment by PublicScam** [comment]
Is this still a valid pull request or can it be closed?

**Comment by socialhack** [comment]
Yes, this issue can be disregarded. piwik is operational and also upholds DNT.

**Pull request closed without merging**
