### PR TITLE
privacy policy translation to portuguese

### PR DESCRIPTION
**Pull request by tiagocasalribeiro**
Hi @PublicScam, I had already done most of the translation, but for some reason it was deleted on your side. I was unable to make a pull request from my repo so I deleted it and forked again. so here it is. I was unable to found the file to edit so i could translate the questionnaire.

### CODE REVIEW

**Comment by tiagocasalribeiro** [comment]
There is a part of the questionnaire that was already translated, I think it's ok to make it active. As I get to know where to edit to translate the rest of the text, I'll do it.

**Comment by PublicScam** [comment]
Hi @tiagocasalribeiro, sorry for the circumstances. Since it was important to Mozilla that we change our policy, I quickly ran a script to simply replace it for all languages.
To make work easier for you in future, you might be interested in the `git show` command, which allows you to view the content of a file in history. That way you can easily restore the work you've already done.
In order to change content of the backend, I need to refer to @Sonstwer.

**Comment by Sonstwer** [comment]
Hi, 
the Questionnaire is not reachable via github, i have to login to update the documents.
i can send you a copy of the english questionaire and can update the Questions after the translation.
please send me your mailadress to Andreas [.] Czak ((a)) akvorrat [.] at
i will answer to you asap @tiagocasalribeiro

**Comment by tiagocasalribeiro** [comment]
@Sonstwer just sent you an email, I think the most important is to translate the questions ASAP but keep the text to send in the email in english, because it has a lot of technical lingo. I can work on translating that too but I really think it should be kept in english, for the sake of precision. I also don't think I can have it ready before the end of the public consultation.

**Pull request merged**
