### PR TITLE
Trying to push new corrections to the FR translation

### PR DESCRIPTION
**Pull request by piks3l**
all in the title

### CODE REVIEW

**Comment by PublicScam** [comment]
Hello, this seems to be based on some pretty old setup. Did you request this by fault? It doesn't really seem like it would fit.

**Comment by piks3l** [comment]
This is unfortunate, where is the current version? I'm not a big expert of git, to be honest I'm a bit lost. We received complaints on the translation. I'd like to correct that.

**Comment by PublicScam** [comment]
Hi, the files you committed do not exist in the current setup any more. The only exception is the FAQ, which is located under a different directory now and has changed in some aspects.
It would be convenient if you rebased your local repository and integrated the changes. To help you save some time, I capitalized the word 'neutrality' in commit 3763074617fd9812951e439f0fedab594acb1c04.
Next time, please don't forget to check if your branch is up to date before working on new changes, so we save some time. I wonder because your last commit 41618a94341729a02f750aeef5a4cff3cee7c6f6 was already based on the newer setup.

**Comment by Sonstwer** [comment]
Hi,
we'll try to merge all the changes - after they're accepted you can review them at
https://beta.savetheinternet.eu

in the meantime the privacy policy has been updated, if you can help with the translation here:
https://akv.titanpad.com/sti-privacypolicy
that would be great

Greets
Andreas

**Comment by PublicScam** [comment]
Hello, a little update on this. We received commit d6ccf0be668f9e2488064ef341ff4e70df0862c4 and 69442b820aecfc9160daa6c4a0596ce3376e7047 which both took care about the French translations.

**Comment by piks3l** [comment]
Yep, I know, I'll proofread the latest to check *everything* and do the consultation afterwards. I'll notify the webmaster (dunno if it's you) when it can go live

**Comment by PublicScam** [comment]
That's nice of you, but please update your fork before starting to work this time. Your current public fork (at least the your branches master and devel) is based on a version we used a few months ago, in the meanwhile it was set up completely new.

**Pull request closed without merging**
