### PR TITLE
French translation (check before pushing into prod tho)

### PR DESCRIPTION
**Pull request by piks3l**
Hey, this is the actual pull request, I made an error. So tell if there is something missing :)

### CODE REVIEW

**Comment by musha68k** [comment]
Hi @piks3l  in addition to the new design we've also got a [simpler translation flow](https://github.com/Netzfreiheit/STI-UI/blob/master/README.md) now but there have also been some changes to the texts themselves (mostly the intro/header part).

This is how the new site looks and (will be deployed either today or tomorrow):

https://beta.savetheinternet.eu

**Comment by piks3l** [comment]
come on, really?

i'll check it up again this week but i won't be able to deliver before next week

**Comment by socialhack** [comment]
@piks3l if this is a real problem to you, @Sonstwer can help out and create those files based on your previous work. We can try to get this done this week, but that depends on our remaining workload. You'd still have to review the work on the staging site. Do you prefer this option to you doing the transposition into files?

**Comment by piks3l** [comment]
the problem isn't to create the files, we managed to compile the website. it's the time of translating. So no worries

**Comment by socialhack** [comment]
All the text besides the subtitle stayed exactly the same. So it is just a copy paste job.

**Comment by piks3l** [comment]
that's good to know

**Comment by PublicScam** [comment]
French translation was added in a562e37e4d6a26c6ee678d6f84868bf881596633. However, we have an open issue #155 concerning the French translation you might be interested in.

**Pull request closed without merging**
